'use strict';

// CITY ACTIONS
export const SELECT_CITY = 'SELECT_CITY';
export const REQUEST_WEATHER = 'REQUEST_WEATHER';
export const RECEIVE_WEATHER = 'RECEIVE_WEATHER';
export const CHANGE_RANGE = 'CHANGE_RANGE';
export const REQUEST_NEARBY_CITIES = 'REQUEST_NEARBY_CITIES';
export const CHANGE_DESIRED_WEATHER = 'CHANGE_DESIRED_WEATHER';
export const RECEIVE_WEATHER_FORECAST = 'RECEIVE_WEATHER_FORECAST';
export const REQUEST_WEATHER_FORECAST = 'REQUEST_WEATHER_FORECAST';

// NAVIGATION ACTIONS
export const BACK = 'BACK';